###
### [store]
###
### 数据库连接相关配置
###
[store]
  host = "127.0.0.1"
  database = "test"
  # 数据库类型
  dialect = "mysql"
  username = "root"
  timezone = "+09:00"
  operatorsAliases = false
  logging = false